### PR TITLE
Use a custom theme

### PR DESCRIPTION
**Pull request by PeterJCLaw**
This lets us push our theme customisations into the theme, rather than trying to bolt them on afterwards. While there hopefully won't be many changes, this is a much neater solution.

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
The deploy fail is almost certainly a result of me changing the theme submodule to our own fork (https://github.com/sourcebots/Mainroad). Shame that netlify doesn't run `git submodule sync` after changing branch.

**Comment by RealOrangeOne** [comment]
@PeterJCLaw looks like youre correct, after clearing the build cache, everything deployed fine!

**Comment by RealOrangeOne** [comment]
If you're actually trying to move everything from overriding here to into the theme fork, you'll also want to move https://github.com/sourcebots/website/tree/master/layouts for completeness

**Comment by PeterJCLaw** [comment]
@RealOrangeOne the intent of this PR was to move _theme_ related things into the theme, as well as to make it easier to modify the general site theme.

IMO the events related things in the [layouts](https://github.com/sourcebots/website/tree/master/layouts) directory aren't strictly _theme_ things and should therefore stay where they are.

I must admit to not entirely understanding the way that the layouts folder is meant to work -- should I be using that to override the theme behaviour instead of forking it?

**Comment by RealOrangeOne** [comment]
Generally yes, I think the idea is to use `layouts/`, as files in it are overlayed on top of the theme and used instead of theme files. However with some of the changes that we made, it involved internalising a whole file for a single-line change.

Now I've looked in the `layouts/` directory, I think youre right, everything in there is fine to stay

**Review by RealOrangeOne — APPROVED** [review]

**Pull request merged**
